'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class conditions_equipements
    Public Property id_equipement As String
    Public Property id_condition As String

    Public Overridable Property conditions As ICollection(Of condition) = New HashSet(Of condition)
    Public Overridable Property equipements As ICollection(Of equipement) = New HashSet(Of equipement)

End Class
