'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class conditions_equipements
    Public Property id_equipement As String
    Public Property id_condition As String

    Public Overridable Property conditions As ICollection(Of condition) = New HashSet(Of condition)
    Public Overridable Property equipements As ICollection(Of equipement) = New HashSet(Of equipement)

End Class
