'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class emprunteur
    Public Property id_emprunteur As String

    Public Overridable Property individu As individu
    Public Overridable Property prets As ICollection(Of pret) = New HashSet(Of pret)
    Public Overridable Property retours As ICollection(Of retour) = New HashSet(Of retour)

End Class
