'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class equipement
    Public Property id_equipement As String
    Public Property nom As String
    Public Property description As String
    Public Property categorie As String
    Public Property etat As String
    Public Property date_enregistrement As Nullable(Of Date)
    Public Property date_indisponible As Nullable(Of Date)
    Public Property date_retrait As Nullable(Of Date)

    Public Overridable Property prets As ICollection(Of pret) = New HashSet(Of pret)
    Public Overridable Property retours As ICollection(Of retour) = New HashSet(Of retour)
    Public Overridable Property conditions_equipements As conditions_equipements
    Public Overridable Property responsabilites_equipements As responsabilites_equipements

End Class
