'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class equipement
    Public Property id_equipement As String
    Public Property nom As String
    Public Property description As String
    Public Property categorie As String
    Public Property etat As String
    Public Property date_enregistrement As Nullable(Of Date)
    Public Property date_indisponible As Nullable(Of Date)
    Public Property date_retrait As Nullable(Of Date)

End Class
