'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class individu
    Public Property id_individu As String
    Public Property nom As String
    Public Property prenom As String
    Public Property adresse As String
    Public Property departement As String
    Public Property statut As Nullable(Of Integer)
    Public Property telephone As String
    Public Property courriel As String
    Public Property motdepasse As String

    Public Overridable Property emprunteurs As emprunteur
    Public Overridable Property preteurs As preteur

End Class
