'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class individu
    Public Property id_individu As String
    Public Property nom As String
    Public Property prenom As String
    Public Property adresse As String
    Public Property departement As String
    Public Property statut As Nullable(Of Integer)
    Public Property telephone As String
    Public Property courriel As String
    Public Property motdepasse As String

    Public Overridable Property emprunteurs As emprunteur
    Public Overridable Property preteurs As preteur

End Class
