'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbmultiEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbmultiEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property conditions() As DbSet(Of condition)
    Public Property conditions_equipements() As DbSet(Of conditions_equipements)
    Public Property emprunteurs() As DbSet(Of emprunteur)
    Public Property equipements() As DbSet(Of equipement)
    Public Property individus() As DbSet(Of individu)
    Public Property preteurs() As DbSet(Of preteur)
    Public Property prets() As DbSet(Of pret)
    Public Property responsabilites() As DbSet(Of responsabilite)
    Public Property responsabilites_equipements() As DbSet(Of responsabilites_equipements)
    Public Property retards() As DbSet(Of retard)
    Public Property retours() As DbSet(Of retour)

End Class
