'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbmultiEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbmultiEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property conditions() As DbSet(Of condition)
    Public Property conditions_equipements() As DbSet(Of conditions_equipements)
    Public Property emprunteurs() As DbSet(Of emprunteur)
    Public Property equipements() As DbSet(Of equipement)
    Public Property individus() As DbSet(Of individu)
    Public Property preteurs() As DbSet(Of preteur)
    Public Property prets() As DbSet(Of pret)
    Public Property responsabilites() As DbSet(Of responsabilite)
    Public Property responsabilites_equipements() As DbSet(Of responsabilites_equipements)
    Public Property retards() As DbSet(Of retard)
    Public Property retours() As DbSet(Of retour)

End Class
