'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pret
    Public Property id_pret As String
    Public Property id_emprunteur As String
    Public Property id_preteur As String
    Public Property id_equipement As String
    Public Property date_emprunt As Nullable(Of Date)
    Public Property date_retour As Nullable(Of Date)

    Public Overridable Property emprunteur As emprunteur
    Public Overridable Property preteur As preteur
    Public Overridable Property equipement As equipement

End Class
