'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pret
    Public Property id_pret As String
    Public Property id_emprunteur As String
    Public Property id_preteur As String
    Public Property id_equipement As String
    Public Property date_emprunt As Nullable(Of Date)
    Public Property date_retour As Nullable(Of Date)

    Public Overridable Property emprunteur As emprunteur
    Public Overridable Property preteur As preteur
    Public Overridable Property equipement As equipement

End Class
