'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class responsabilites_equipements
    Public Property id_equipement As String
    Public Property id_responsabilite As String

    Public Overridable Property responsabilites As ICollection(Of responsabilite) = New HashSet(Of responsabilite)
    Public Overridable Property equipements As ICollection(Of equipement) = New HashSet(Of equipement)

End Class
