'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class retard
    Public Property id_retard As String
    Public Property id_retour As String
    Public Property constat As String
    Public Property montant_dommages As Nullable(Of Double)

    Public Overridable Property retour As retour

End Class
